### ISSUE TITLE
Request for custom keybindings

### ISSUE THREAD

**Issue by nl253** [xgi/castero#1]
Would it be able to have custom keybindings or at the very least emacs and vim modes?

**Comment by tihnessa** [comment]
## Implementation plan

Issue #1 is already closed and implemented by commit `e8c81dc`. The current code exposes configurable single-key bindings in `[keys]`, maps printable and named curses keys, and renders configured bindings in help text. This plan therefore focuses on verifying and completing the existing implementation without duplicating behavior.

The issue does not require dedicated Vim/Emacs profiles because custom bindings satisfy its preferred outcome. Multi-key sequences and chords are not specified and remain out of scope.

1. **Create a working branch**

   Create `issue-1-custom-keybindings-audit` from the current HEAD.

2. **Write tests first**

   - Add tests using genuinely remapped keys, rather than deriving inputs from the default configuration.
   - Verify printable characters, named curses keys, `ENTER`, and `SPACE`.
   - Verify a remapped key invokes the intended action and the old default no longer does.
   - Cover generic commands and perspective-specific commands in the existing perspective test modules.
   - Verify custom help bindings appear in the footer and generated help text.
   - Verify config migration adds the `[keys]` section while preserving existing user settings.
   - Preserve and test the documented collision rule: overlapping bindings perform only the first matching operation.

3. **Write code to make the tests pass**

   - Complete or refine key translation in `castero/display.py`.
   - Route command handling through configured keys in `castero/perspective.py` and each perspective subclass.
   - Keep defaults and supported key names in `castero/templates/castero.conf`.
   - Ensure configuration migration preserves existing values.
   - Keep the footer and runtime help synchronized with configured bindings.
   - Avoid production changes where the existing implementation already passes the stronger tests.

4. **Run tests**

   Run focused tests first:

   ```bash
   python -m pytest tests/test_config.py tests/test_display.py tests/test_perspective_*.py
   ```

   Then run the complete suite:

   ```bash
   python -m pytest tests
   ```

5. **Repeat until requirements are met**

   Address failures and rerun focused and full suites until custom bindings, default compatibility, migration, and displayed help all behave consistently.

6. **Before committing**

   - Update relevant codebase documentation if key resolution or input routing changes.
   - Update `README.md` with a custom-keybinding example, supported syntax, collision behavior, and the fact that bindings take effect after restarting.
   - Confirm the changelog accurately records the feature.
