### ISSUE TITLE
Volume control does not work on Ubuntu Touch

### ISSUE THREAD

**Issue by charlesDelaware** [xgi/castero#111]
I use mpv from the terminal on Ubuntu Touch and the volume buttons work fine to control the volume but, Castero will only play at one volume regardless of the volume level set on the device. I even set player = mpv in the config file but, that didn't help.

**Comment by xgi** [comment]
I don't have a good way of experimenting since I don't have a similar device, but I'm not sure there's much I can do for this because all the playback features are delegated to the mpv plugin. So if that plugin isn't correctly accessing the device volume that's probably an external issue.

However I have been considering adding volume controls within castero (with keybinds). Not ideal, but hopefully that will at least make it usable for you.

**Comment by charlesDelaware** [comment]
Thanks for your reply. Volume controls within Castero would be great and  would make it more useful on my phone for sure! I am currently using castero on Ubuntu Touch to curate the podcasts and then drop out of castero and into the download directory. from there I invoke mpv directly on the podcast directory I want (which gets a bit cumbersome). castero is awesome btw and works great on my laptops. Thanks for building it and keep up the great work!
