### ISSUE TITLE
'Too many or too few link tags' error on adding a podcast

### ISSUE THREAD

**Issue by metastork** [xgi/castero#120]
Tried to add one apparently legit RSS feed and it's giving the following error:

```
FeedStructureError: RSS feed's channel has too many or too few link tags; expected 1, was: 0. The corresponding title is: Professor Blastoff -- Press h for help
```
The URL is: https://www.omnycontent.com/d/playlist/aaea4e69-af51-495e-afc9-a9760146922b/b1f718a8-3177-4a31-b123-ab3c016c6dca/3123c838-cb12-4cf0-9cc2-ab3c016cda19/podcast.rss

**Comment by xgi** [comment]
The error seems correct, this is not technically valid RSS (can also check with this: https://validator.w3.org/feed/). When I wrote the validator in castero I think I was a bit optimistic about the world, haha. Since this missing tag doesn't seem strictly necessary, I'll add an exemption for it in the validator.
