### ISSUE TITLE
New feed items don't get added to top of episode list

### ISSUE THREAD

**Issue by raniesantos** [xgi/castero#137]
castero 0.8.1
Linux Mint 19.3

[screen recording](https://giant.gfycat.com/MadeupSpicyDiplodocus.mp4)

[pastebin config file](https://pastebin.com/z9876Bku)

I've also experienced this with my other podcasts, but Syntax was the only one with new episodes that I could have in this recording. Definitely not a feed-specific problem.

**Comment by xgi** [comment]
Can you check if the missing episode is actually in the list but just not appearing at the top? You can filter with `/` so for your example maybe try filtering for "refine your process" which should be the latest episode.

I was able to replicate this behavior which is why I'm assuming it's the case. I'll look into why the sorting is messed up.

**Comment by raniesantos** [comment]
I just checked, the new items do get added, but not at the top.

**Comment by xgi** [comment]
Fixed with #138 by making episodes explicitly sorted by publish date. Thanks!
