### ISSUE TITLE
Related to #77 add config value or hotkey to show (unplayed) count instead of (played/total)

### ISSUE THREAD

**Issue by raniesantos** [xgi/castero#142]
I find that the total episode count of each podcast is rarely ever relevant to me and I care more about the number of episodes I **haven't** listened to.

**Comment by xgi** [comment]
Perhaps something changed since this was created, but I believe the client does show the unplayed count (and the total). Feeds start by default with all episodes being considered unplayed. While looking at this I considered adding an option to show played count instead, but I don't think there's much value in that (for the reason you said). Sorry for taking a while to respond; let me know if I'm wrong. Thanks!
