### ISSUE TITLE
Reloading feeds not working

### ISSUE THREAD

**Issue by alrayyes** [xgi/castero#158]
Running castero 0.8.2 and since about month ago feed reloads don't work anymore. Exporting opml, deleting the database and re-importing opml does import all the feeds properly.

**Comment by xgi** [comment]
I wasn't able to replicate this (i.e. reloading appears to work for me). I recall a bug related to this some time ago, which I believe was fixed before 0.8.2, but I'll publish a new version within a week or so which may resolve this. Sorry I can't be much help.

**Comment by alrayyes** [comment]
No worries. A verbose / debug argument would help immensely to troubleshoot issues like this. It’s probably one of my feeds that castero isn’t parsing correctly.

**Comment by tranalbert** [comment]
Can confirm that the same issue happens when there is an issue with a particular feed or if one of the feed urls no longer exists

**Comment by xgi** [comment]
This has been fixed with #159. If reloading an individual feed fails, it will no longer crash the rest of the reloading process (which was causing no feeds to get updated). It also fixes (for most cases) a common cause of this problem: a website being changed to redirect to a new feed URL.

Thanks, and sorry for the delay!
