### ISSUE TITLE
Save position within the podcast, retrieve position

### ISSUE THREAD

**Issue by dammmn** [xgi/castero#161]
When playing the podcast, something interrupts so I stop the podcast and I will get back to this later. When I quit the client, position inside the podcast changes and podcast starts from the beginning. Is there any support for saving the position temporarily ? I was not able to locate such a feature in the available docs. 

Thank you !

P.S.: thanks for a great podcast client ! Really great work.

**Comment by xgi** [comment]
This was actually implemented some time ago, but I held off on releasing a new version because I had planned on adding another small feature. That's on hiatus now, so I can double-check that this feature (saving episode progress) still works as a standalone and increment the version within a few days.
Thanks!

**Comment by dammmn** [comment]
> This was actually implemented some time ago, but I held off on releasing a new version because I had planned on adding another small feature. That's on hiatus now, so I can double-check that this feature (saving episode progress) still works as a standalone and increment the version within a few days.
> Thanks!

Very good, I was about to start dig into your sources this coming weekend to figure this out but since it's been implemented  there is no need for me to burn the cycles.
