### ISSUE TITLE
Remove html from podcast metadata

### ISSUE THREAD

**Issue by rabuzarus** [xgi/castero#25]
If the metadata of a podcast entry contains html (e.g. images) it should be removed. The metadata should only contain pure text

At the moment it is looking like the following:
![castero_html_metadata](https://user-images.githubusercontent.com/3750381/52363575-4b89ac80-2a43-11e9-865d-738cc020e939.png)

**Comment by xgi** [comment]
Yeah, this is something I've wanted to do for a while. I put it off for some time because I wasn't sure if I wanted to try replicating some of the style elements in plaintext (i.e. lists, links). It's probably worthwhile to just strip out the contents; I'm sure people have solved this kind of thing before. Thanks for the suggestion!
