### ISSUE TITLE
Checking feeds from certain URL from a config file

### ISSUE THREAD

**Issue by thepenguinthatwants** [xgi/castero#33]
For now after testing it a bit seems like all the feeds are needed to import manually.

Would be nice to add feeds from ./user/config/castero/urls -file

**Comment by xgi** [comment]
Thanks for the suggestion! There's a few aspects to this I think.

First, I'm not a fan of having a user-managed list of feeds, since I want to handle all storage in my own format. I would have to deal with consistency issues when i.e. an episode in the database refers to a now removed feed. It just doesn't seem worthwhile.

However, I would like to add a way to add feeds in bulk / allow for importing feeds from other clients. My main concern is that, although it would be easy to add support for a text file of URLs (i.e. one feed per line), practically speaking there's no real benefit here since you would have to compile the list manually anyway. It seems that many clients support exporting to OPML, so I can look further into that format. It'll probably be some time before I can add proper parsing for it, though.

**Comment by xgi** [comment]
Added support for importing OPML files with 0.6.0.
