### ISSUE TITLE
Next page in a feed after setting max_episodes

### ISSUE THREAD

**Issue by qymspace1** [xgi/castero#44]
I have 
```set max_episodes = 30```

How would I got to the next time items of the feed?

And btw question: 
How to search for episodes in a feed?

**Comment by xgi** [comment]
I don't think I understand your question. Setting max_episodes means that the client will only load that many episodes per feed. The only way to show additional episodes is to change that setting.

There is also currently no way to search in feeds.

**Comment by qymspace1** [comment]
Thank you for replying. You understand me perfectly. Yes I wanted to be able to see the next 30 items and so forth

**Comment by xgi** [comment]
I'm going to close this since I assume the issue was just misunderstanding the setting. It's purpose is really just for people who want to limit storage space on the disk if they have feeds with i.e. thousands of episodes. If you don't want a limit you can set it to -1 (the default) which lets you scroll through everything.

Let me know if I misinterpreted something. Thanks!

**Comment by xgi** [comment]
I also just created #45 to add searching.
