### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by rien333** [xgi/castero#90]
After some of the performance related tweaks  recently added to castero,  I noticed that CPU usage is way higher than usual, even when the application is idle. Just having it open causes it to use more than 70% of an i7 core. (kinda annoying, bc my fans turn on and all that).

I'm running linux 5.5, with castero build from git. 

Not sure how to debug, but if you have suggestions I can look into them.

**Comment by xgi** [comment]
Yeah, this is probably caused by my reduction of the refresh delay. The display literally updates 1000x more than it did before. I'll reduce this to a more reasonable amount and add a config setting for it.

The problem I'm having is that castero has assumed for a long time that the input delay is directly correlated with how often the screen needs to update. The way things generally worked were, the user presses a button (like "down" for the next feed), the client freezes for 3ms imperceptibly while we query the database for a list of episodes, and then the display would update with the new content.

The way things work now are that the database requests are threaded, so we have to wait for the next display cycle before it can be refreshed. For example if I set the delay to 50ms, when the user presses the key a thread starts for the database which finishes in 3ms, but then the user has to wait 47ms for it to actually show up. But of course for some users with massive databases this request could take 300ms+, so we don't want their client to freeze up after each input.

There are a few things I want to do to resolve that, because in the future I would like the refresh rate to be as high as it currently is. For one, I mostly just need to look over how CPU heavy a display update is, and optimize it (keep in mind the delay was literally a second before, so it was never really a big concern). I also want to try experimenting with having threads be able to override the refresh delay when there's new content -- that's probably an ideal solution, but is also multithreading hell.

But for now I'll just reduce the refresh rate (and add an setting for it). Thanks for the report; sorry about the wall of text.

**Comment by rien333** [comment]
Thanks for the detailed reply!

**Comment by xgi** [comment]
#91 adds a setting for the refresh delay which is set to 70ms by default, in comparison to the 1ms it was before. It's a bit difficult for me to narrow down an ideal default since I honestly have a very good CPU, but this reduces my idle usage from ~5.1% to ~0.3%.

I created a separate issue #92 to look into what I described above in order to reduce usage in general, and to hopefully allow me to lower the delay in the future. I also created #93 which is for a slightly different issue, where scrolling through many feeds can temporarily spike CPU usage. This isn't as immediate of a concern for me, however.

I'll look into these over the next week. If my change here didn't work for you, feel free to reopen this issue. Thanks!
