### ISSUE TITLE
Does castero clean downloaded episodes?

### ISSUE THREAD

**Issue by lcabrini** [xgi/castero#97]
First of all, sorry if this is answered someplace, I couldn't find it.

Background: I happen to live in one of those parts of the world where Internet connectivity is not always the best. So I like to download a bunch of episodes when I can and then listen to them locally. However, I would need these podcasts to be removed after some time (possibly a configurable number of days). I use podcasts primarily to listen languages that I am learning or trying to keep alive. Sometimes I hear something that I want to rip out of an episode, via Audacity to later add to Anki. That is why I would like episodes to at least remain on my drive at least long enough for me to decide if there is something I want out of it.

So the question is if castero automatically cleans downloaded episodes and if so, after how long? I used gPodder for a long time, but of late it has started crashing frequently for me (on Fedora 31) so am looking for alternatives. Castero looks very promising.

gPodder of course does allow me to automatically select an interval after which the episode gets cleaned off. However, it uses the date the episode was deleted and not the date I downloaded it, so it doesn't really help me that much.

If castero doesn't support this, I guess I could just write a script that stats the downloaded files and deletes them if they are too old. I could run this as a cron job. I think that may even be a better solution than to burden a podcatcher with this task.

**Comment by xgi** [comment]
To answer the title question, no, castero doesn't automatically delete episodes.

I can understand the use case for this, but IMO it's not something that a significant number of people would be interested in. So I would be hesitant to add it since this would just feel like feature-creep to me. I do think it's somewhat similar to #16 (although I haven't worked on that one for a similar reason); I could imagine that if I created a headless command to automatically download episodes I could also have an option to clean up outdated ones. But personally I just feel like this would add more bloat than functionality.

I'll leave this open as a suggestion (especially if there are other opinions) but I don't plan on working on it at this time. Thanks!

**Comment by lcabrini** [comment]
The more I think about it, the more convinced I am that castero should *not* try to clean up episodes. Let it do what it does best, a podcatcher. Cleaning should be the responibility of a separate process, something that the user can run as a cronjob, for instance.

**Comment by raniesantos** [comment]
If I create an alias/script that does the downloads purging for me, will Castero recognize that the files are gone or will it still show that the files are there when they really aren't?

**Comment by xgi** [comment]
@raniesantos It's totally safe to delete them from outside of castero, but ideally only when castero isn't running. The client checks whether an episode file exists once while running, and then that state is saved until castero is restarted.

**Comment by xgi** [comment]
Also, I'm going to close this since I'm pretty confident it's not something I'm interested in adding to castero. It will still be referenced from #16 as a secondary potential addition, although as mentioned before it's unlikely I'll implement that, either.
